Serverless function
logzio/azure-serverless pull request #1
Opened 2024-01-17 14:18 UTC by bardabun

I've made several improvements to the 'azure-serverless' project, enhancing log shipping from Azure to Logz.io. Key updates include:

1. Refined deployment steps for easier setup.
2. Improved configuration template with clearer parameters.
3. Detailed instructions for streaming Azure service data.
4. New backup mechanism for unshipped logs.
5. Updated documentation with helpful visuals.

These changes aim to streamline user experience and boost functionality. Looking forward to your feedback.

2024-01-18 07:45 UTC, mirii1994 requested changes
Great great work!!!
Please see my comments :)

2024-01-18 07:45 UTC, mirii1994 commented on LogzioShipper/__init__.py
> +    # conn_str=os.getenv("AZURE_STORAGE_CONNECTION_STRING"),  # On local
Please remove commented out line if it's unnecessary :)

2024-01-18 07:45 UTC, mirii1994 commented on LogzioShipper/__init__.py
> +# logging.getLogger().addHandler(logging.StreamHandler(sys.stdout))
Please remove commented out line if it's unnecessary :)

2024-01-18 07:45 UTC, mirii1994 commented on LogzioShipper/__init__.py
> +# LOGZIO_URL = os.getenv("LOGZIO_LISTENER")
Please remove commented out line if it's unnecessary :)

2024-01-18 07:45 UTC, mirii1994 commented on LogzioShipper/__init__.py
> +# LOGZIO_TOKEN = os.getenv("LOGZIO_TOKEN")
Please remove commented out line if it's unnecessary :)

2024-01-18 07:45 UTC, mirii1994 commented on LogzioShipper/__init__.py
> +@backoff.on_exception(backoff.expo, requests.exceptions.RequestException, max_tries=3)
Can we make the max_tries configurable?

2024-01-18 07:45 UTC, mirii1994 commented on LogzioShipper/__init__.py
> +        response = session.post(LOGZIO_URL, params={"token": LOGZIO_TOKEN, "type": "eventHub"}, headers=HEADERS, data=batch_str)
Let's allow the type to be configurable, with default value of eventHub

2024-01-18 07:45 UTC, mirii1994 commented on LogzioShipper/__init__.py
> +            print(f"Adding batch of size {len(local_log_batch)} to the sending queue.")
If there's a logger let's use it throughout the code, instead of prints

2024-01-18 07:45 UTC, mirii1994 commented on README.md
Please rech out to @nico-shishkin for him to review the readme :)

2024-01-18 07:45 UTC, mirii1994 commented on deployments/azuredeploylogs.json
> +            "defaultValue": "logs",
Let's change it to a name that is more clear on the purpose of the container - if it's for backup logs, then something like "backup logs"

2024-01-18 07:45 UTC, mirii1994 commented on deployments/azuredeploylogs.json
> +        "ContainerName":
Let's change the parameter name to a name that is more clear on the purpose of the container - if it's for backup logs, then something like "backup logs"

2024-01-18 07:45 UTC, mirii1994 commented on deployments/azuredeploylogs.json
> +                "description": "The Logz.io listener URL for your region."
Please reach out to @nico-shishkin to go over the descriptions of that parameters

2024-01-18 07:45 UTC, mirii1994 commented on deployments/azuredeploylogs.tf
> +provider "azurerm" {
If we include deployment via Terraform, we need to include instructions for this method in our readme

2024-01-21 14:39 UTC, mirii1994 commented on README.md
> +- Version 0.0.1:
```suggestion
- **0.0.1**:
```

2024-01-21 14:40 UTC, mirii1994 approved these changes
Great work!!!!
Let's wait for Nico's review of the documentation, and then we'll proceed :)

2024-01-23 13:12 UTC, nico-shishkin approved these changes

2024-02-26 09:20 UTC, merged